spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_data_jpa
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true

      hbm2ddl.auto: validate
    open-in-view: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
app:
  image:
    bucket: D:\java\IT Academy\lessons\module04(spring)\lesson07\Spring-Starter\images